using System.Collections.Frozen;

namespace ClassLibrary1;

//https://en.wikipedia.org/wiki/List_of_Frozen_characters?utm_source=chatgpt.com


public record Character(string Name, string Description)
{
    public readonly static FrozenSet<Character> L = new[] {
        new Character("Anna","Anna of Arendelle is the main protagonist of the Frozen film series. She is the second-born daughter of King Agnarr and Queen Iduna, the younger sister of Elsa, and the contemporary ruler of Arendelle. During their childhood, an accident involving Elsa's magic created a rift between the two sisters, leaving Anna devoid of love and human connection. Despite this, she remained optimistic and hopeful, albeit lonely. When Elsa's powers inadvertently set off an eternal winter in Arendelle, Anna embarks on a perilous journey to save her kingdom and mend her relationship with her sister. Throughout the series, Anna is portrayed as a kind, selfless, and determined"),
        new Character("Elsa","Elsa of Arendelle is the deuteragonist of the Frozen film series. She is the elder daughter of King Agnarr and Queen Iduna, the older sister of Anna, and the former queen of Arendelle. Elsa was born with the magical ability to create and manipulate ice and snow. As a child, she accidentally injured Anna with her powers, prompting their parents to separate them until Elsa learned to control her abilities. After their parents' death, Elsa was crowned queen, but her powers were exposed during her coronation, causing her to flee Arendelle. Elsa eventually learns to embrace her powers and becomes the protector of the Enchanted Forest. Throughout the series, Elsa is portrayed as a reserved, introspective, and selfless"),
        new Character("Olaf","Olaf is a fictional character from Disney's Frozen franchise, produced by Walt Disney Animation Studios. Olaf is first presented in Frozen (2013) as an animated snowman created by Elsa and Anna in their childhood. He then reappears as an anthropomorphic character in the film as Anna searches for her runaway sister in Elsa's ice palace. Olaf is an optimistic, outgoing, and comical snowman who dreams of experiencing summer. He is known for his innocence, naivety, and childlike wonder, as well as his love for warm hugs. Olaf is voiced by Josh Gad in the films and other media."),
        new Character("Kristoff",
            """
            Kristoff Bjorgman is a fictional character from Disney's Frozen franchise, produced by Walt Disney Animation Studios. He is a rugged ice harvester who becomes the love interest of Princess Anna. Kristoff is first introduced in Frozen
            (2013) as a loner who lives in the mountains with his reindeer companion, Sven. He is hired by Anna to guide her to the North Mountain to find her sister, Elsa. Throughout the series, Kristoff is portrayed as a kind, loyal, and selfless individual who is willing to help others in need. He is known for his rugged appearance, practical skills, and love for his reindeer. Kristoff is voiced by Jonathan Groff in the films and other media.
            """),
        new Character("Sven","Sven is a fictional character from Disney's Frozen franchise, produced by Walt Disney Animation Studios. He is a reindeer who serves as the loyal companion of Kristoff Bjorgman. Sven is first introduced in Frozen (2013) as Kristoff's reindeer and best friend. He accompanies Kristoff on his journey to help Princess Anna find her sister, Elsa. Throughout the series, Sven is portrayed as a loyal, affectionate, and playful reindeer who shares a close bond with Kristoff. He is known for his friendly nature, expressive eyes, and love for carrots. Sven is voiced by Jonathan Groff in the films and other media."),
        new Character("Hans","Hans Westergaard is a fictional character from Disney's Frozen franchise, produced by Walt Disney Animation Studios. He is the main antagonist of Frozen (2013) and a minor character in Frozen II (2019). Hans is introduced in Frozen as the youngest prince of the Southern Isles who travels to Arendelle to seek his fortune. He initially presents himself as a charming and noble suitor to Princess Anna, but he reveals his true nature when he attempts to usurp the throne of Arendelle. Throughout the series, Hans is portrayed as a manipulative, deceitful, and power-hungry individual who seeks to gain power at any cost. He is known for his cunning, charisma, and ambition. Hans is voiced by Santino Fontana in the films and other media."),
        new Character("Duke of Weselton","The Duke of Weselton is a fictional character from Disney's Frozen franchise, produced by Walt Disney Animation Studios. He is a minor antagonist in Frozen (2013) and a minor character in Frozen II (2019). The Duke is introduced in Frozen as the pompous and greedy ruler of Weselton who seeks to exploit Arendelle's resources for his own gain. He initially presents himself as a friendly and amiable dignitary, but he reveals his true intentions when he conspires against Queen Elsa. Throughout the series, the Duke is portrayed as a conniving, self-serving, and cowardly individual who seeks to profit from Arendelle's misfortune. He is known for his arrogance, cowardice, and greed. The Duke is voiced by Alan Tudyk in the films and other media."),
        new Character("Pabbie","Pabbie is a fictional character from Disney's Frozen franchise, produced by Walt Disney Animation Studios. He is the leader of the Hidden Folk, a group of mystical creatures who inhabit the Enchanted Forest. Pabbie is introduced in Frozen II (2019) as a wise and benevolent troll who possesses magical abilities. He aids Queen Elsa and Princess Anna in uncovering the truth about their family's past and the origins of Elsa's powers. Throughout the series, Pabbie is portrayed as a wise, compassionate, and enigmatic figure who guides the protagonists on their journey. He is known for his mystical powers, ancient wisdom, and protective nature. Pabbie is voiced by Ciarán Hinds in the films and other media."),
        new Character("Oaken","Oaken is a fictional character from Disney's Frozen franchise, produced by Walt Disney Animation Studios. He is the owner of Wandering Oaken's Trading Post and Sauna, a trading post located in the mountains near Arendelle. Oaken is introduced in Frozen (2013) as a friendly and jovial shopkeeper who offers shelter to Princess Anna, Kristoff, and Sven during a blizzard. He is known for his boisterous personality, distinctive accent, and love of sauna baths. Throughout the series, Oaken is portrayed as a kind, generous, and humorous individual who provides assistance to the protagonists. He is known for his catchphrase \"Yoo-hoo!\" and his family-friendly demeanor. Oaken is voiced by Chris Williams in the films and other media."),
        new Character("Bulda","Bulda is a fictional character from Disney's Frozen franchise, produced by Walt Disney Animation Studios. She is a troll and the adoptive mother of Kristoff Bjorgman. Bulda is introduced in Frozen (2013) as a wise and caring troll who raises Kristoff and his reindeer companion, Sven. She is known for her nurturing nature, maternal instincts, and protective attitude towards Kristoff. Throughout the series, Bulda is portrayed as a loving, supportive, and compassionate figure who guides Kristoff on his journey. She is known for her wisdom, kindness, and sense of humor. Bulda is voiced by Maia Wilson in the films and other media."),
        new Character("Marshmallow","Marshmallow is a fictional character from Disney's Frozen franchise, produced by Walt Disney Animation Studios. He is a giant snow monster created by Queen Elsa to protect her ice palace from intruders. Marshmallow is first introduced in Frozen (2013) as a formidable and imposing creature who guards Elsa's fortress. He is known for his immense size, strength, and resilience, as well as his loyalty to Elsa. Throughout the series, Marshmallow is portrayed as a fierce, protective, and misunderstood character who serves as Elsa's guardian. He is known for his intimidating appearance, gentle heart, and desire to protect his creator. Marshmallow is voiced by Paul Briggs in the films and other media."),
        new Character("Grand Pabbie","Grand Pabbie is a fictional character from Disney's Frozen franchise, produced by Walt Disney Animation Studios. He is the leader of the Hidden Folk, a group of mystical creatures who inhabit the Enchanted Forest. Grand Pabbie is introduced in Frozen (2013) as a wise and benevolent troll who possesses magical abilities. He aids Queen Elsa and Princess Anna in uncovering the truth about Elsa's powers and their family's past. Throughout the series, Grand Pabbie is portrayed as a wise, compassionate, and enigmatic figure who guides the protagonists on their journey. He is known for his mystical powers, ancient wisdom, and protective nature. Grand Pabbie is voiced by Ciarán Hinds in the films and other media."),
        new Character("King Agnarr","King Agnarr of Arendelle is a fictional character from Disney's Frozen franchise, produced by Walt Disney Animation Studios. He is the father of Princess Anna and Queen Elsa, and the husband of Queen Iduna. King Agnarr is introduced in Frozen II (2019) as the ruler of Arendelle who seeks to protect his family from a dark secret. He is known for his wisdom, compassion, and devotion to his daughters. Throughout the series, King Agnarr is portrayed as a loving, supportive, and protective father who guides Anna and Elsa on their journey. He is known for his leadership, integrity, and selflessness. King Agnarr is voiced by Alfred Molina in the films and other media."),
        new Character("Queen Iduna","Queen Iduna of Arendelle is a fictional character from Disney's Frozen franchise, produced by Walt Disney Animation Studios. She is the mother of Princess Anna and Queen Elsa, and the wife of King Agnarr. Queen Iduna is introduced in Frozen II (2019) as a mysterious and enigmatic figure who plays a pivotal role in the history of Arendelle. She is known for her kindness, grace, and selflessness. Throughout the series, Queen Iduna is portrayed as a loving, supportive, and protective mother who guides Anna and Elsa on their journey. She is known for her wisdom, compassion, and devotion to her family. Queen Iduna is voiced by Evan Rachel Wood in the films and other media."),
        new Character("Yelena","Yelena is a fictional character from Disney's Frozen franchise, produced by Walt Disney Animation Studios. She is the leader of the Northuldra tribe, a group of indigenous people who inhabit the Enchanted Forest. Yelena is introduced in Frozen II (2019) as a strong and courageous warrior who seeks to protect her people from outside threats. She is known for her bravery, resilience, and loyalty to her tribe. Throughout the series, Yelena is portrayed as a fierce, independent, and compassionate leader who guides her people on their journey. She is known for her wisdom, strength, and determination. Yelena is voiced by Martha Plimpton in the films and other media."),
        new Character("Honeymaren",
            """
            Honeymaren is a fictional character from Disney's Frozen franchise, produced by Walt Disney Animation Studios. She is a member of the Northuldra tribe, a group of indigenous people who inhabit the Enchanted Forest. Honeymaren is introduced in Frozen II (2019) as a free-spirited and adventurous character who befriends Queen Elsa and Princess Anna. She is known for her kindness, compassion, and love of nature. Throughout the series, Honeymaren is portrayed as a caring, supportive, and resourceful individual who aids the protagonists on their journey. She is known for her connection to the elements, her bond with the Enchanted Forest, and her friendship with the Northuldra tribe. Honeymaren is voiced by Rachel Matthews in the films and other media.
            """),
        new Character("Mattias","Mattias is a fictional character from Disney's Frozen franchise, produced by Walt Disney Animation Studios. He is the leader of the Arendelle Guard and a former soldier who served in the Enchanted Forest. Mattias is introduced in Frozen II (2019) as a brave and honorable warrior who befriends Queen Elsa and Princess Anna. He is known for his loyalty, courage, and sense of duty. Throughout the series, Mattias is portrayed as a protective, compassionate, and selfless individual who aids the protagonists on their journey. He is known for his leadership, integrity, and devotion to his comrades. Mattias is voiced by Sterling K. Brown in the films and other media."),
        new Character("Lieutenant Destin Mattias","Lieutenant Destin Mattias is a fictional character from Disney's Frozen franchise, produced by Walt Disney Animation Studios. He is a soldier who served in the Arendelle Guard and the Enchanted Forest. Lieutenant Mattias is introduced in Frozen II (2019) as a loyal and dedicated officer who befriends Queen Elsa and Princess Anna. He is known for his bravery, resilience, and sense of duty. Throughout the series, Lieutenant Mattias is portrayed as a protective, compassionate, and selfless individual who aids the protagonists on their journey. He is known for his leadership, integrity, and devotion to his comrades. Lieutenant Mattias is voiced by Jason Ritter in the films and other media.")
    }.ToFrozenSet();


    public readonly static FrozenSet<Character> Empty = Enumerable.Empty<Character>().ToFrozenSet();
}

